### PR TITLE
Fixes #1453: Directly install podman of using brew

### LINKED ISSUE #1453: Building Containerfile failing on amd64
```
Writing manifest to image destination
[1/2] STEP 2/19: RUN microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y
error running container: from /usr/bin/crun creating container for [/bin/sh -c microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y]: unknown version specified
: exit status 1
time="2024-03-25T14:18:54Z" level=error msg="did not get container create message from subprocess: EOF"
Error: building at STEP "RUN microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y": while running runtime: exit status 1
Error: Process completed with exit code 1.
```
https://github.com/skupperproject/skupper-router/actions/runs/8421554600/job/23058755390#step:5:20

### PR DESCRIPTION
**Pull request by ganeshmurthy**

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]
it seems to work; there's not arguing with "works"

**Comment by ganeshmurthy** [comment]
> it seems to work; there's not arguing with "works"

I copied this code directly from @fgiorgetti 
https://github.com/skupperproject/skupper/blob/659023da41a6cda8b41c71e4cb34a6a4cb398b8c/.circleci/config.yml#L314C1-L335

**Comment by fgiorgetti** [comment]
@ganeshmurthy maybe on an upcoming PR, you could turn this into a local action.

**Comment by ganeshmurthy** [comment]
> @ganeshmurthy maybe on an upcoming PR, you could turn this into a local action.

You mean create a custom action that all these scripts can then use ?

**Pull request merged**
