### PR TITLE
ISSUE-22: remove in-repo web console and documentation

### LINKED ISSUE #22: Remove console code and build tooling

### PR DESCRIPTION
**Pull request by kgiusti**
Adds a stub HTML index that links to skupper.io

This closes #22

### CODE REVIEW

**Review by jiridanek — COMMENTED** [review]
Just a note that removing `tests/system_tests_console.py` leaves a hole in the testing: now there is only one other test (`system_tests_websockets.py`) that interacts with router management through websockets. (And that other remaining test pretty much only connects and disconnects.)

You can say in response that any management tests are more or less equivalent (the console essentially does what the qd_ tools do), which is probably true.

**Review by ganeshmurthy — APPROVED** [review]

**Comment by kgiusti** [comment]
> Just a note that removing `tests/system_tests_console.py` leaves a hole in the testing: now there is only one other test (`system_tests_websockets.py`) that interacts with router management through websockets. (And that other remaining test pretty much only connects and disconnects.)
> 
> You can say in response that any management tests are more or less equivalent (the console essentially does what the qd_ tools do), which is probably true.

@jiridanek yes the testing for this is limited, but we don't have a specific feature that uses the libwebsockets functionality in the router right now.  We've left the libwebsockets-related code in the router because we'll need to use it for future features it later.  At that point we'll need to introduce a set of CI tests for that.

**Comment by kgiusti** [comment]
Hi @pwright - this patch (tries) to remove references to the web console from the documentation.  I think I caught all of them - let me know what you think.

**Comment by kgiusti** [comment]
@pwright Nevermind - I see you've submitted a PR to nuke all the docs.  Cool - I'll wait for you to check that in then rebase this one. Thanks.

**Comment by pwright** [comment]
@kgiusti not going to nuke docs at this time, found one more console mention at https://github.com/skupperproject/skupper-router/blame/main/docs/books/modules/user-guide/viewing-log-entries.adoc#L33

**Review by pwright — APPROVED** [review]

**Pull request merged**
