### PR TITLE
Fixes #1465: End the listener vanflow record when the listener is del…

### LINKED ISSUE #1465: Listener van flow record does not terminate/end when listener is deleted
The listener delete functionality does delete the listener.

### PR DESCRIPTION
**Pull request by ganeshmurthy**
…eted and not wait until the last connection on that listener is deleted

### CODE REVIEW

**Review by kgiusti — APPROVED** [review]
Patch looks good to me.
Can @fgiorgetti validate that it fixes the issue he found?

**Comment by ganeshmurthy** [comment]
> Patch looks good to me. Can @fgiorgetti validate that it fixes the issue he found?

I talked to @fgiorgetti about testing. He wants the PR to be committed to main and he will test immediately. I will go ahead and merge this and if it does not fix the issue, we will revert immediately.

**Comment by fgiorgetti** [comment]
@ganeshmurthy @kgiusti That CI test is now passing, I have also confirmed manually that the collector is receiving the appropriate flow record to terminate the listener.
Thank you!

**Comment by ganeshmurthy** [comment]
> @ganeshmurthy @kgiusti That CI test is now passing, I have also confirmed manually that the collector is receiving the appropriate flow record to terminate the listener. Thank you!

@fgiorgetti thank you very much for testing

**Pull request merged**
