### PR TITLE
remove docs

### PR DESCRIPTION
**Pull request by pwright**
addresses #157

### CODE REVIEW

**Comment by pwright** [comment]
@kgiusti  I wonder whether I should also remove the man page docs, given that we don't intend users to ever start the router from the cli?

**Comment by kgiusti** [comment]
> @kgiusti I wonder whether I should also remove the man page docs, given that we don't intend users to ever start the router from the cli?

I'd keep them, certainly the "qdmanage/qdstat" stuff still applies - but that's just my $0.02 so I'm happy to go along with the general consensus

**Review by kgiusti — APPROVED** [review]
LGTM.  The conflict github is complaining about is where I changed the version to 2.0.0-SNAPSHOT in the common/attributes file.  This patch removes that file which is The Right Thing To Do....

**Comment by pwright** [comment]
@kgiusti  resolved conflict, ok to merge?

**Comment by kgiusti** [comment]
> @kgiusti resolved conflict, ok to merge?

@pwright merge man, merge!

**Pull request merged**
