### PR TITLE
Add notes from Ken's presentation

### PR DESCRIPTION
**Pull request by jiridanek**
Incomplete so far, I intend to review the recording(s) and fill out the details later.

(Switch the preview in GitHub to rendered document to see what this looks like. Especially the atrocious diagram is worth looking at, for the blunt artistic impact of the thing.

### CODE REVIEW

**Review by kgiusti — APPROVED** [review]
Nicely done!

**Comment by ganeshmurthy** [comment]
@jiridanek Do you want to merge this and continue working on the TODO sections later ?

**Comment by jiridanek** [comment]
I think I'll either do that, or merge in what's in a reasonable shape and keep the rest in my branch for later work.

**Comment by ganeshmurthy** [comment]
> I think I'll either do that, or merge in what's in a reasonable shape and keep the rest in my branch for later work.

Either way, please do merge.

**Pull request merged**
