### PR TITLE
Enable s390x Travis CI build; Add coredump analyzer for Travis

### PR DESCRIPTION
**Pull request by jiridanek**
https://app.travis-ci.com/github/jiridanek/skupper-router/builds/254021857

```
$ sudo sysctl -w kernel.core_pattern="coredump.%e.%p"
sysctl: permission denied on key "kernel.core_pattern"
```

Looks like we have to live with the default pattern, which seems to be `core`.

The working of the coredump analysis can be tested by replacing the CI script with

```
python3 -c 'import os; import signal; os.kill(os.getpid(), signal.SIGABRT)'
```

### CODE REVIEW

**Comment by jiridanek** [comment]
```
60: test_get_image_jpg (system_tests_http2_tls.Http2TestTlsStandaloneRouter) ... skipped 'Python 3.7 or greater, Quart 0.13.0 or greater and curl needed to run http2 tests'
```

https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/578785860#L4657

That line is worrisome. All requirements for the test should be fulfulled!

**Comment by ganeshmurthy** [comment]
> ```
> 60: test_get_image_jpg (system_tests_http2_tls.Http2TestTlsStandaloneRouter) ... skipped 'Python 3.7 or greater, Quart 0.13.0 or greater and curl needed to run http2 tests'
> ```
> 
> https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/578785860#L4657
> 
> That line is worrisome. All requirements for the test should be fulfulled!
Somehow this function is returning True, which is why the tests are being skipped. Surely something is wrong with one of those three functions. This might be unrelated but this function - https://github.com/skupperproject/skupper-router/blob/main/tests/system_tests_http2.py#L39 - never returns False

**Comment by jiridanek** [comment]
I'll try debug it tomorrow. Find out what exactly is returning (not true).

**Comment by ganeshmurthy** [comment]
> I'll try debug it tomorrow. Find out what exactly is returning (not true).

Thanks much @jiridanek

**Comment by jiridanek** [comment]
> > I'll try debug it tomorrow. Find out what exactly is returning (not true).
> 
> Thanks much @jiridanek

The reason was the following, https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/578900073#L298

The `pip install` was not updating jinja2 and markupsafe packages, because they were already installed systemwide. New version of quart did not work with the old versions of jinja2 or markupsafe. The return of `None` in the function to check Python version did not matter; None is falsey, so that works fine.

**Comment by jiridanek** [comment]
So, currently, there is only a single real issue as far as I can tell

https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/578903357#L4619

(and https://github.com/skupperproject/skupper-router/issues/543)

**Pull request merged**
