### PR TITLE
Fixes #1687: Solved duplicate port issue

### LINKED ISSUE #1687: system_tests_http.test_https_get failing on Fedora 41
```
======================================================================
ERROR: test_https_get (system_tests_http.RouterTestHttp.test_https_get)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.13/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              encode_chunked=req.has_header('Transfer-encoding'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/http/client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                          server_hostname=server_hostname)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA cert does not include key usage extension (_ssl.c:1020)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router-3.0.0-build/skupper-router-3.0.0/tests/system_tests_http.py", line 385, in test_https_get
    self.assert_get_cert("https://localhost:%d" % r.ports[2])
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/skupper-router-3.0.0-build/skupper-router-3.0.0/tests/system_tests_http.py", line 71, in assert_get_cert
    self.assertEqual('HTTP test\n', self.get_cert("%s/system_tests_http.txt" % url))
                                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/skupper-router-3.0.0-build/skupper-router-3.0.0/tests/system_tests_http.py", line 65, in get_cert
    return opener.open(url).read().decode('utf-8')
           ~~~~~~~~~~~^^^^^
  File "/usr/lib64/python3.13/urllib/request.py", line 489, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.13/urllib/request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "/usr/lib64/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.13/urllib/request.py", line 1367, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        context=self._context)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA cert does not include key usage extension (_ssl.c:1020)>
```

### PR DESCRIPTION
**Pull request by ganeshmurthy**

### CODE REVIEW

**Comment by jiridanek** [comment]
Just a few drive-by comments. I don't see how this happened and I fear that patching it up in `system_tests_http.py` is not the right spot, since whatever happened may be also affecting other tests?

**Comment by ganeshmurthy** [comment]
> I don't see how this happened and I fear that patching it up in `system_tests_http.py` is not the right spot

Yep, I agree. I looked at the `get_port()` function in system_test.py and it seemed to me that the duplicate port problem can never happen. But it does happen intermittently when running on copr - https://download.copr.fedorainfracloud.org/results/packit/skupperproject-skupper-router-1686/fedora-41-x86_64/08334013-skupper-router/builder-live.log.gz

This problem does not happen in any of our other CI tests.

To temporarily fix this problem, I added a local dict. If we see this problem happen more widely, we should revisit the `get_port()` function

**Comment by ganeshmurthy** [comment]
> I added a local dict

The fix I tried has failed, the problem might be in the router. I am investigating further

**Comment by ganeshmurthy** [comment]
The issue was not related to the duplicate port. The actual issue is TLS failure. I have updated the issue with the new description - https://github.com/skupperproject/skupper-router/issues/1687

I am closing this PR

**Pull request closed without merging**
